# read the data from the subdata file which is generated by data_read.R

mydata=read.csv("~/Desktop/git_repo/household_power_consumption_subdata.csv",header=TRUE)


file_name<-"~/Desktop/git_repo/plot1.png"

png(
  file=file_name,
  width     = 480,
  height    = 480,
  units     = "px",
  #res       = 300,
  #pointsize = 4 
)

# data source: Global_active_power
d1=mydata$Global_active_power
hist(d1,main="Global Active Power",col = "red", xlab="Global Active Power (kilowatts)")
dev.off()
