# read the data from the subdata file which is generated by data_read.R

mydata=read.csv("~/Desktop/git_repo/household_power_consumption_subdata.csv",header=TRUE)

## combine date and time column, add a new column of date_time with the format '%d/%m/%Y %H:%M:%S'
mydata$date_time=strptime(paste0(mydata$Date," ",mydata$Time),format='%d/%m/%Y %H:%M:%S')


file_name<-"~/Desktop/git_repo/plot3.png"
png(
  file=file_name,
  width     = 480,
  height    = 480,
  units     = "px",
  #res       = 300,
  #pointsize = 4 
)

# data source: Global_active_power

plot(mydata$date_time,mydata$Sub_metering_1,type='l',ylab='Energy sub metering',xlab='',col='black')
lines(mydata$date_time,mydata$Sub_metering_2,type='l',ylab='',xlab='',col='red')
lines(mydata$date_time,mydata$Sub_metering_3,type='l',ylab='',xlab='',col='blue')
legend("topright",legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),lty=c(1,1,1),col=c('black','red','blue'))


dev.off()


